# Generated by Django 5.1.5 on 2025-01-23 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"verbose_name": "사용자", "verbose_name_plural": "사용자들"},
        ),
        migrations.AlterField(
            model_name="user",
            name="social_kakao_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
